### ISSUE TITLE
Kanri?

### ISSUE THREAD

**Issue by taxilly** [maxpowa/npomf#17]
In config/core.js line 112

`// Session options for Kanri. !! YOU MUST SET THESE FOR KANRI TO WORK !!`

I understand that it's some auth. page, but could you explain what this is for, do I even need it?

**Comment by Aareksio** [comment]
It's basic control panel for the application.

**Comment by maxpowa** [comment]
As @Aareksio said, basic control panel. It's not required in any way for the app to run correctly. I'm actually planning on removing it since it's really badly designed.

Naming came from some of my more cringy weeb nature showing through, **kanri** translates as “management.”

**Comment by taxilly** [comment]
I can get it authorize my account to use the OAuth, but it just keeps looping back to login, see:

``` bash
GET /images/sign_in_github_pressed.png 304 6.226 ms - -
GET /auth/github 302 14.479 ms - 0
GET /auth/github/callback?code=c03a3ac678dc82b71ccf 302 1410.760 ms - 70
GET /kanri/stream 302 5.361 ms - 68
GET /kanri/login 200 326.553 ms - 1807
...
...
...
```

I can see it gets the 302 to redirect but nothing happens?
My core.js kanri conf:

```
config.GITHUB_CLIENT_ID = secret.clientID;
config.GITHUB_CLIENT_SECRET = secret.clientSecret;

config.SESSION_OPTIONS = {
        name: 'kanri.session',
        secret: secret.Key,
        maxAge: (86400 * 1000), 
        secureProxy: true,
        domain: "https://movw-space.cf"
}
```

**Comment by Aareksio** [comment]
Your session is not persisting - try setting `secureProxy` to `false`.

**Comment by twentytwoo** [comment]
Still not working unfortunately...
Perhaps it's due to the secret/key; I wasn't really sure what those are so I just put it to `secret` since it looked like the simplest option.
