### ISSUE TITLE
Server responded with 0 code.

### ISSUE THREAD

**Issue by billyprice1old** [maxpowa/npomf#19]
Im getting a error saying Server responded with 0 code. when uploading a img file

**Comment by installgen3** [comment]
https://a.lainfile.pw/47/bash_history.txt

**Comment by jithatsonei** [comment]
you really shouldnt be running a pomf

**Comment by installgen3** [comment]
The following sequence of command should fix it:

```
LS
ls
lls
LS
ls
```

**Comment by installgen3** [comment]
If the issue still persists, try

```
cd /var/www/
ls
chmod 777 * files/
ls
cd files/
ls
cd /var/www/
ls
```

**Comment by billyprice1** [comment]
I have already chmoded it and started it will chmod when i do ls it green

**Comment by billyprice1** [comment]
That did not sort it  useing this version worked https://github.com/ygbhf/npomf-modify

**Comment by installgen3** [comment]
my fucking sides you took it seriously you little fucknut

**Comment by lkd70** [comment]
I see /g/ has found its way to github...

**Comment by installgen3** [comment]
@lkd70 do you literally not realize who I am

**Comment by lkd70** [comment]
I 'literally' don't.

**Comment by installgen3** [comment]
@lkd70 protip my name ends with a 2 and I got banned for posting :eggplant:

**Comment by maxpowa** [comment]
This thread is c a n c e r.
